version: '3.8'

services:
  # LLM Gateway Application with Smart Router
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: llm-gateway-test
    ports:
      - "8080:8080"
      - "9090:9090"  # Metrics port
    environment:
      - CONFIG_FILE=configs/config.yaml
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - OPENAI_API_KEY=sk-test-key-for-testing
      - ANTHROPIC_API_KEY=claude-test-key-for-testing
      - BAIDU_API_KEY=baidu-test-key-for-testing
    volumes:
      - ./configs:/app/configs:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: llm-gateway-postgres-test
    environment:
      POSTGRES_DB: gateway
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway -d gateway"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: llm-gateway-redis-test
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_test_data: