# LLM Gateway Configuration

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  host: "localhost"
  port: 5432
  username: "gateway"
  password: "password"
  database: "gateway"
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

auth:
  jwt_secret: "your-jwt-secret-key-change-this-in-production"
  jwt_expiration: "24h"
  enable_api_key: true

logging:
  level: "info"       # debug, info, warn, error
  format: "json"      # json, text
  output: "stdout"    # stdout, stderr, file path

metrics:
  enabled: true
  path: "/metrics"
  port: 9090

# Smart Router Configuration (Week4)
smart_router:
  strategy: "round_robin"  # round_robin, weighted_round_robin, least_connections, health_based
  health_check_interval: "30s"
  failover_enabled: true
  max_retries: 3
  circuit_breaker:
    enabled: true
    threshold: 5
    timeout: "30s"
    max_requests: 3
  metrics_enabled: true
  # Provider weights for weighted_round_robin strategy
  weights:
    openai: 10
    anthropic: 8
    baidu: 5

# Provider configurations
providers:
  openai:
    enabled: true
    api_key: "${OPENAI_API_KEY:-sk-test-key}"
    base_url: "https://api.openai.com/v1"
    timeout: "30s"
    retry_count: 3
    
  anthropic:
    enabled: true
    api_key: "${ANTHROPIC_API_KEY:-claude-test-key}"
    base_url: "https://api.anthropic.com"
    timeout: "30s"
    retry_count: 3
    
  baidu:
    enabled: true
    api_key: "${BAIDU_API_KEY:-baidu-test-key}"
    base_url: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop"
    timeout: "30s"
    retry_count: 3