# LLM Gateway Production Configuration
# Copy this file and customize for your environment

providers:
  openai:
    name: "OpenAI"
    type: "openai"
    enabled: true
    base_url: "https://api.openai.com/v1"
    api_key_env: "OPENAI_API_KEY"
    timeout: 60s
    retry_count: 3
    rate_limit: 60
    weight: 1
    priority: 1
    models: ["gpt-3.5-turbo", "gpt-4", "gpt-4-turbo", "gpt-4o", "gpt-4o-mini"]
    
    # Production retry configuration
    retry_policy:
      max_retries: 3
      base_delay: 1s
      max_delay: 30s
      backoff_factor: 2.0
      retryable_errors: ["network", "server", "timeout", "rate_limit"]
    
    # Cost management
    cost_tracking: true
    cost_limits:
      daily_limit: 100.0      # $100 per day
      monthly_limit: 1000.0   # $1000 per month
      per_request_limit: 10.0 # $10 per request
      currency: "USD"
    
    # Monitoring
    metrics_enabled: true
    health_check_url: "/health"
    
  anthropic:
    name: "Anthropic"
    type: "anthropic"
    enabled: true
    base_url: "https://api.anthropic.com/v1"
    api_key_env: "ANTHROPIC_API_KEY"
    timeout: 60s
    retry_count: 3
    rate_limit: 60
    weight: 1
    priority: 2
    models: ["claude-3-haiku", "claude-3-sonnet", "claude-3-opus", "claude-3.5-sonnet"]
    
    # Production retry configuration
    retry_policy:
      max_retries: 3
      base_delay: 1s
      max_delay: 30s
      backoff_factor: 2.0
      retryable_errors: ["network", "server", "timeout", "rate_limit"]
    
    # Cost management
    cost_tracking: true
    cost_limits:
      daily_limit: 100.0
      monthly_limit: 1000.0
      per_request_limit: 10.0
      currency: "USD"
    
    # Monitoring
    metrics_enabled: true
    health_check_url: "/health"
    
  baidu:
    name: "百度文心一言"
    type: "baidu"
    enabled: true
    base_url: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop"
    api_key_env: "BAIDU_API_KEY"
    timeout: 60s
    retry_count: 3
    rate_limit: 60
    weight: 1
    priority: 3
    models: ["ernie-bot", "ernie-bot-turbo", "ernie-bot-4"]
    
    # Production retry configuration
    retry_policy:
      max_retries: 3
      base_delay: 1s
      max_delay: 30s
      backoff_factor: 2.0
      retryable_errors: ["network", "server", "timeout", "rate_limit"]
    
    # Cost management
    cost_tracking: true
    cost_limits:
      daily_limit: 500.0     # Higher limit for Baidu (CNY equivalent)
      monthly_limit: 5000.0
      per_request_limit: 50.0
      currency: "USD"
    
    # Monitoring
    metrics_enabled: true
    health_check_url: "/health"

# Global server configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

# Database configuration (if needed)
database:
  type: "postgres"
  host: "localhost"
  port: 5432
  database: "llm_gateway"
  ssl_mode: "prefer"
  
# Redis configuration (if needed)
redis:
  host: "localhost"
  port: 6379
  database: 0
  
# Monitoring
monitoring:
  metrics_port: 9090
  health_check_path: "/health"
  log_level: "info"